services:
  # utilise en dev et staging
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ./volumes/elastic/data:/usr/share/elasticsearch/data
      - ./volumes/elastic/logs:/usr/share/elasticsearch/logs
    environment:
      - discovery.type=single-node
      - cluster.name=cluster_name
      - network.host=0.0.0.0
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=true

  # utilise en dev et staging
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      # FIXME : necessaire d'avoir un token temporaire ou ko ailleurs ?
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${ELASTICSEARCH_TOKEN:-temp_token}
    depends_on:
     - elasticsearch

  # utilise uniquement en staging pour tester image, pas pour tester scripts R et autre
  cert_dashboard:
    build: .
    container_name: cert_dashboard
    ports:
      - "127.0.0.1:8181:8180"
    env_file:
      - .env
    depends_on:
     - elasticsearch
    volumes:
      - .:/srv/cert_dashboard/R
      - ./volumes/sqlite:/srv/cert_dashboard/sqlite
      - ./env-docker.R:/srv/cert_dashboard/R/env.R
    # FIXME : impossible de visualiser dashboard dans navigateur
    command: Rscript /srv/cert_dashboard/R/new_dashboard.R
